# Generated by Django 5.0.2 on 2025-06-15 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indicador",
            fields=[
                (
                    "indicador_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("nombre_indicador", models.CharField(max_length=100)),
                ("meta", models.PositiveIntegerField()),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("D", "diario"),
                            ("S", "semanal"),
                            ("M", "mensual"),
                            ("A", "anual"),
                        ],
                        default="semanal",
                        max_length=100,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "Indicadores",
            },
        ),
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "trabajador_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Trabajadores",
            },
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "registro_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateTimeField(blank=True, null=True)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "indicador",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventas.indicador",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventas.trabajador",
                    ),
                ),
            ],
            options={
                "db_table": "Registros",
            },
        ),
    ]
