# Generated by Django 5.0.2 on 2025-06-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro",
            name="indicador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ventas.indicador"
            ),
        ),
        migrations.AlterField(
            model_name="registro",
            name="trabajador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ventas.trabajador"
            ),
        ),
    ]
